### ISSUE TITLE
Syntax specific

### ISSUE THREAD

**Issue by szarouski** [alienhard/SublimeAllAutocomplete#12]
Hi, would it be possible to add support for syntax exclusions? So that for example I can disable completions in javascript or css? Thank you.

**Comment by stdavis** [comment]
This would be great. Did anything ever happen with it?

**Comment by alienhard** [comment]
I'll look into it. Seems like that has become a popular feature request.

On Tue, Jun 23, 2015 at 10:26 AM, Scott Davis <notifications@github.com>
wrote:

> This would be great. Did anything ever happen with it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alienhard/SublimeAllAutocomplete/issues/12#issuecomment-114579016>
> .
>



-- 

__________________________

www.adrian-lienhard.ch

twitter.com/adrianlienhard

**Comment by magnus-staberg** [comment]
Yep, it'd be  👍

**Comment by alienhard** [comment]
Support for syntax-specific exclusions is supported now. Please see the README for details. Thanks for the patience :)
