### ISSUE TITLE
Prefer Sublime's default completion for CSS

### ISSUE THREAD

**Issue by jomo** [alienhard/SublimeAllAutocomplete#28]
This plugin works great for most things. I like it. :+1: 

However, in CSS (or SCSS) files I prefer sublime's own auto-completion because it recognizes keywords, inserts colons, spaces and semicolons.

Sublime's options are still available, but they aren't the ones first selected so you would need to scroll down.

``` CSS
/* · = space */
/* | = cursor */

/* CSS keywords */
padding|            /* AllAutoComplete */
padding:·|          /* Sublime built in completion */

/* CSS values */
padding:·inherit|   /* AllAutoComplete */
padding:·inherit;|  /* Sublime built in completion */
```

**Comment by Frexuz** [comment]
:+1: Vote up

**Comment by alienhard** [comment]
Support for syntax-specific exclusions is supported now. Please see the README for details.
