### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Gabriel-p** [alienhard/SublimeAllAutocomplete#41]
I'm running build 3065 on Linux (elementary OS 0.2) and I can't seem to get this package to work.

I type and nothing happens, I'm not even sure how this package should work because I see _nothing_.

Other packages installed:

* Alignment
* Autowrap
* Dictionaries
* Git
* LatexTools
* oauthlib
* Package Control
* Sublime Bookmarks
* Wrap Plus

**Comment by alienhard** [comment]
This package adds additional entries to the standard ST autocomplete widget. If you don't see it it's probably not related to that package.

This page might help: https://www.sublimetext.com/docs/3/auto_complete.html (make sure autocomplete isn't disabled, and try to open autocomplete with the keyboard shortcut as described on that page).
