### ISSUE TITLE
Option to exclude paths

### ISSUE THREAD

**Issue by mim-Armand** [alienhard/SublimeAllAutocomplete#44]
It would be great if it was possible to exclude some path / drive from the search (for empty drives, like SD readers etc. checking for file names will cause a "No Disk" error!)

thx,

,m

**Comment by alienhard** [comment]
@mim-Armand would you be able to help me reproduce this problem? The package doesn't open any files, it just sends messages to existing view objects provided by the Sublime API. Hence I'm not clear how this could cause a problem in your case.

**Comment by mim-Armand** [comment]
Hey Adrian,
Thanks for your response, this is for a while ago, back then I was using a PC and as (and if) I remember (my apology to not including more details and screenshots originally) the problem was that either the plugin or ST API were trying to scan the path and that would cause the "No Disk" error ( for instance maybe when there were an open file from a CD that wasn't in the drive anymore ), so disabling the plug-in would prevent this from happening, specially back then I had bunch of mounted images and drives that were constantly changing..
Now it's a while I'm using Mac and haven't used the plugin anymore but if you couldn't reproduce this issue on your side please go ahead and close it, I'll let you know (and maybe re-open it) as/if I encountered the problem again in the future,
Again thank you so much for your great great work, keep it up buddy,

**Comment by alienhard** [comment]
Ok, thanks for the feedback.
