### ISSUE TITLE
conflict with emmet plugin

### ISSUE THREAD

**Issue by alex1012** [alienhard/SublimeAllAutocomplete#45]
I have a trouble with this plugin (AllAutocomplete). When i write in my CSS file some emmet alias, like "dib" and press a tab key, i get some words from my files, but not required property. Can i create some settings to your plugin for press some else button for call plugin work? Or maybe you know better solution. I am very grateful for the help.

**Comment by alienhard** [comment]
I'm not entirely sure I understand... would it solve your problem if there was a setting that allowed you to disable AllAutocomplete in css files?

**Comment by zeshanshani** [comment]
@alienhard I'd second you on that thought. I'm facing the same issue as @alex1012. This is even worse when working with SCSS files.

**Comment by alienhard** [comment]
Support for syntax-specific exclusions is supported now. Please see the README for details.
