### ISSUE TITLE
Is there a way to add Autocomplete words all by myself?

### ISSUE THREAD

**Issue by wufeng87** [alienhard/SublimeAllAutocomplete#49]
Thanks.
Best regards

**Comment by alienhard** [comment]
No, this plugin only completes words from open files (of course you could have a file with all the special definitions you want to be able to complete and keep it as an open tab).

But maybe a better solution for what you're trying to do are Sublime Snippets: https://github.com/alienhard/SublimeAllAutocomplete/issues/49
