### ISSUE TITLE
Package not appear in package control 

### ISSUE THREAD

**Issue by zayanit** [alienhard/SublimeAllAutocomplete#50]
I try to search for the package in package control and it doesn't appear
![screen shot 2016-09-25 at 2 02 58 pm](https://cloud.githubusercontent.com/assets/2796596/18814916/55e78864-8329-11e6-9d30-6a8278c158dd.png)

**Comment by alienhard** [comment]
Maybe because you have already installed it? Is it missing in both "Install Package" and "List Package"?

I'm pretty sure this isn't a general problem since this package has been installed over 600 times every day in the past week (https://packagecontrol.io/packages/All%20Autocomplete).
