### ISSUE TITLE
don't mess with system's autocomplete

### ISSUE THREAD

**Issue by craigcosmo** [alienhard/SublimeAllAutocomplete#51]
Hi,

I have my sublime customized autocomplete and sublime default autocomplete. They work great. Now I have this tabs related autocomplete, great too.

One problem, allAutoComplete will suggest what I already had by default, in a different way.

I normally have completion like `console.log($0)`, what I do is  I press `con` + `tab` to get that.

Now when I do that, I get `console.log` or `console`. You can see there is missing `()`

I understand this plugin will suggest keyword using indexing from open tabs. Now if you could teach the plugin to ignore the autocompletes already in in the system, don't try to suggest that. It will awesome.

**Comment by canoeberry** [comment]
Having just implemented my own version of all auto-complete (more on that in my own issue) I am not sure this is possible. Auto complete in sublime works by allowing everyone to get in on the act and produce their own set of completions. There is no mechanism that I am aware of to look at what has already been generated by other plugins or the system itself.

**Comment by alienhard** [comment]
@canoeberry thanks, that's also my understanding
