### ISSUE TITLE
"Disable" in 'All Autocomplete.sublime-settings' doesn't work as expected

### ISSUE THREAD

**Issue by pattulus** [alienhard/SublimeAllAutocomplete#59]
I love this plugin for all my coding, but it really gets in the way when I'm writing.

Whenever I want to indent a hyphen list like…

```
- A
- B
    - C
``` 

… I end ud with something like this…

```
- A
- B
--verbose C
``` 

I tried disabling All Autocomplete for Markdown and Plain Text documents:

```
{
    "exclude_from_completion": [
        "md",
        "txt"
    ]
}
```

I also tried using the Syntax Names ("Plain Text", etc.), but I still get the lovely autocompletion. 

Am I doing something wrong here?

**Comment by alienhard** [comment]
@pattulus, what does it say when you hit Control+Shift+P? This should tell you the syntax scope to use in the exclude_from_completion config. In a normal text file, for me it says "text.plain". So I would add "text". Note that "txt" wouldn't match in this case.

**Comment by pattulus** [comment]
@alienhard `text.html.markdown meta.paragraph.markdown`, so I added `text` and `markdown`. It works now as expected.  Thanks.

_PS: I also deactivated the [SmartMarkdown](https://github.com/demon386/SmartMarkdown/issues/42) plugin because there where indentation issues. So it might not have been AllAutocomplete._
