### ISSUE TITLE
How can I autocomplete scss variable?

### ISSUE THREAD

**Issue by MOONLIGHTV** [alienhard/SublimeAllAutocomplete#64]
How can I autocomplete scss variable?
%name and @mixin name are fine, but variable like $name doesn't work.
![0](https://user-images.githubusercontent.com/14039419/41451433-7a48bef2-709f-11e8-9ba7-83970183e015.gif)

**Comment by ashikur11** [comment]
you should use css extended completion it suggest scss variables and mixins also
