### ISSUE TITLE
Add relevant GitHub topics

### ISSUE THREAD

**Issue by dominiksalvet** [alienhard/SublimeAllAutocomplete#67]
Hello! I think that it would be great to add some relevant GitHub topics to this repository. Is it possible? :hugs:

**Comment by alienhard** [comment]
Sure :) Added "sublime" and "autocomplete". If you have others you'd like to see added, let me know.

**Comment by dominiksalvet** [comment]
@alienhard Maybe I would also add [`plugin`](https://github.com/topics/plugin).

**Comment by alienhard** [comment]
Done, and added a few more.
