### ISSUE TITLE
Feature request, Auto complete for react component props

### ISSUE THREAD

**Issue by HanggiAnggono** [alienhard/SublimeAllAutocomplete#69]
Is it possible to have auto complete for react component props?. So you can see what props are available in a component.

**Comment by jsmrcaga** [comment]
This plugin fills your autocomplete list with words it finds in other files, it does not provide parsing/lexing of your files.

This means that it could potentially provide autocompletion for a word found in another file if `extract_completions` exports it, but it won't be able to provide you with a list of a given component props out of the box.

Maybe try with [React IDE](https://packagecontrol.io/packages/React%20IDE), but I haven't tested it

**Comment by HanggiAnggono** [comment]
Thank you for the plugin suggestion, i will close this as it is irrelevant.
